SKILLS = [

    # =========================
    # Programming Languages
    # =========================
    "python",
    "java",
    "c",
    "c++",
    "c#",
    "javascript",
    "typescript",
    "php",
    "ruby",
    "swift",
    "kotlin",
    "go",
    "rust",
    "scala",
    "r",
    "matlab",
    "perl",
    "dart",
    "lua",
    "groovy",
    "objective-c",
    "visual basic",
    "vba",
    "assembly",
    "solidity",
    "fortran",
    "cobol",
    "haskell",
    "elixir",
    "erlang",
    "clojure",
    "shell",
    "bash",
    "powershell",
    "sql",

    # =========================
    # Frontend Development
    # =========================
    "html",
    "html5",
    "css",
    "css3",
    "javascript",
    "typescript",
    "react",
    "react.js",
    "next.js",
    "nextjs",
    "vue",
    "vue.js",
    "angular",
    "angular.js",
    "svelte",
    "sveltekit",
    "ember.js",
    "backbone.js",
    "jquery",
    "bootstrap",
    "tailwind",
    "tailwind css",
    "material ui",
    "mui",
    "chakra ui",
    "ant design",
    "sass",
    "scss",
    "less",
    "styled components",
    "webpack",
    "vite",
    "parcel",
    "babel",
    "eslint",
    "prettier",
    "redux",
    "redux toolkit",
    "zustand",
    "mobx",
    "recoil",
    "context api",
    "react router",
    "react query",
    "tanstack query",
    "web sockets",
    "websocket",
    "web workers",
    "service workers",
    "pwa",
    "progressive web apps",
    "responsive design",
    "dom",
    "virtual dom",
    "ajax",
    "fetch api",
    "web accessibility",
    "aria",
    "frontend development",

    # =========================
    # Backend Development
    # =========================
    "node.js",
    "nodejs",
    "express",
    "express.js",
    "flask",
    "django",
    "django rest framework",
    "fastapi",
    "spring",
    "spring boot",
    "spring mvc",
    "spring security",
    "spring data",
    "hibernate",
    "laravel",
    "symfony",
    "asp.net",
    "asp.net core",
    ".net",
    ".net core",
    "ruby on rails",
    "rails",
    "nestjs",
    "nest.js",
    "gin",
    "fiber",
    "echo",
    "actix",
    "rocket",
    "fastify",
    "koa",
    "hapi",
    "tornado",
    "pyramid",
    "bottle",
    "falcon",
    "phoenix",
    "cakephp",
    "codeigniter",
    "strapi",
    "wordpress",
    "backend development",
    "server-side development",
    "serverless",

    # =========================
    # APIs & Web Services
    # =========================
    "api",
    "api development",
    "rest api",
    "restful api",
    "rest",
    "graphql",
    "grpc",
    "soap",
    "web api",
    "web services",
    "microservices",
    "api gateway",
    "api integration",
    "api testing",
    "postman",
    "swagger",
    "openapi",
    "jwt",
    "json web token",
    "oauth",
    "oauth2",
    "openid connect",
    "authentication",
    "authorization",
    "session management",
    "rate limiting",
    "api versioning",
    "webhooks",
    "cors",
    "http",
    "https",
    "tcp/ip",
    "dns",
    "cdn",

    # =========================
    # Databases
    # =========================
    "sql",
    "mysql",
    "postgresql",
    "postgres",
    "mongodb",
    "sqlite",
    "oracle",
    "mariadb",
    "microsoft sql server",
    "sql server",
    "firebase",
    "redis",
    "cassandra",
    "couchdb",
    "dynamodb",
    "elasticsearch",
    "neo4j",
    "snowflake",
    "databricks",
    "bigquery",
    "redshift",
    "clickhouse",
    "supabase",
    "microsoft access",
    "teradata",
    "db2",
    "hbase",
    "influxdb",
    "arangodb",
    "realm",
    "firestore",
    "amazon aurora",
    "amazon rds",
    "database design",
    "database management",
    "database administration",
    "relational database",
    "nosql",
    "sql queries",
    "pl/sql",
    "t-sql",
    "stored procedures",
    "triggers",
    "views",
    "indexes",
    "database normalization",
    "query optimization",
    "database migration",
    "orm",
    "sqlalchemy",
    "prisma",
    "sequelize",
    "mongoose",
    "entity framework",
    "jdbc",
    "odbc",

    # =========================
    # Data Science & Analytics
    # =========================
    "data science",
    "data analysis",
    "data analytics",
    "data engineering",
    "data mining",
    "data preprocessing",
    "data cleaning",
    "data wrangling",
    "exploratory data analysis",
    "eda",
    "statistical analysis",
    "statistics",
    "probability",
    "hypothesis testing",
    "regression analysis",
    "linear regression",
    "logistic regression",
    "time series analysis",
    "predictive analytics",
    "prescriptive analytics",
    "descriptive analytics",
    "business analytics",
    "quantitative analysis",
    "feature engineering",
    "feature selection",
    "dimensionality reduction",
    "principal component analysis",
    "pca",
    "data visualization",
    "data storytelling",
    "numpy",
    "pandas",
    "matplotlib",
    "seaborn",
    "plotly",
    "bokeh",
    "scipy",
    "statsmodels",
    "polars",
    "dask",
    "pyspark",
    "spark",
    "apache spark",
    "hadoop",
    "hive",
    "pig",
    "kafka",
    "apache kafka",
    "airflow",
    "apache airflow",
    "dbt",
    "etl",
    "elt",
    "data pipelines",
    "data warehouse",
    "data lake",
    "data lakehouse",
    "data modeling",
    "data governance",
    "data quality",
    "data integration",
    "data transformation",
    "data visualization tools",

    # =========================
    # Machine Learning
    # =========================
    "machine learning",
    "ml",
    "supervised learning",
    "unsupervised learning",
    "semi-supervised learning",
    "reinforcement learning",
    "deep learning",
    "artificial intelligence",
    "ai",
    "generative ai",
    "gen ai",
    "large language models",
    "llm",
    "llms",
    "natural language processing",
    "nlp",
    "computer vision",
    "predictive modeling",
    "classification",
    "regression",
    "clustering",
    "decision trees",
    "random forest",
    "random forests",
    "support vector machine",
    "svm",
    "knn",
    "k-nearest neighbors",
    "naive bayes",
    "gradient boosting",
    "xgboost",
    "lightgbm",
    "catboost",
    "ada boost",
    "adaboost",
    "bagging",
    "boosting",
    "ensemble learning",
    "k-means",
    "hierarchical clustering",
    "dbscan",
    "mean shift",
    "anomaly detection",
    "outlier detection",
    "recommendation systems",
    "recommender systems",
    "collaborative filtering",
    "content-based filtering",
    "model evaluation",
    "model validation",
    "cross validation",
    "hyperparameter tuning",
    "grid search",
    "random search",
    "bayesian optimization",
    "overfitting",
    "underfitting",
    "regularization",
    "l1 regularization",
    "l2 regularization",
    "lasso",
    "ridge",
    "elastic net",
    "gradient descent",
    "stochastic gradient descent",
    "sgd",
    "loss functions",
    "confusion matrix",
    "roc auc",
    "precision",
    "recall",
    "f1 score",
    "accuracy",
    "mean squared error",
    "rmse",
    "mae",
    "r squared",
    "mlops",
    "model deployment",
    "model monitoring",
    "model serving",
    "model optimization",
    "model interpretability",
    "explainable ai",
    "xai",
    "shap",
    "lime",
    "mlflow",
    "weights and biases",
    "wandb",
    "dvc",
    "feast",

    # =========================
    # Deep Learning & Generative AI
    # =========================
    "tensorflow",
    "pytorch",
    "keras",
    "jax",
    "mxnet",
    "caffe",
    "theano",
    "onnx",
    "onnx runtime",
    "cuda",
    "cudnn",
    "neural networks",
    "artificial neural networks",
    "ann",
    "convolutional neural networks",
    "cnn",
    "recurrent neural networks",
    "rnn",
    "lstm",
    "gru",
    "autoencoders",
    "variational autoencoders",
    "vae",
    "gan",
    "generative adversarial networks",
    "transformers",
    "attention mechanism",
    "self-attention",
    "bert",
    "gpt",
    "t5",
    "llama",
    "mistral",
    "gemma",
    "hugging face",
    "huggingface",
    "transformers library",
    "sentence transformers",
    "word embeddings",
    "word2vec",
    "glove",
    "fasttext",
    "tokenization",
    "text classification",
    "text generation",
    "text summarization",
    "question answering",
    "named entity recognition",
    "ner",
    "sentiment analysis",
    "text similarity",
    "semantic similarity",
    "semantic search",
    "vector embeddings",
    "vector database",
    "rag",
    "retrieval augmented generation",
    "prompt engineering",
    "prompt optimization",
    "fine tuning",
    "fine-tuning",
    "peft",
    "lora",
    "qlora",
    "reinforcement learning from human feedback",
    "rlhf",
    "function calling",
    "tool calling",
    "ai agents",
    "agentic ai",
    "langchain",
    "langgraph",
    "llamaindex",
    "llama index",
    "chromadb",
    "chroma",
    "pinecone",
    "weaviate",
    "faiss",
    "milvus",
    "qdrant",
    "openai api",
    "google gemini api",
    "gemini api",
    "anthropic api",
    "vertex ai",
    "azure openai",
    "ollama",
    "vllm",
    "hugging face hub",

    # =========================
    # Computer Vision
    # =========================
    "opencv",
    "opencv-python",
    "image processing",
    "image classification",
    "image segmentation",
    "object detection",
    "face detection",
    "face recognition",
    "ocr",
    "optical character recognition",
    "yolo",
    "yolov5",
    "yolov8",
    "yolov9",
    "yolov10",
    "yolov11",
    "rcnn",
    "faster rcnn",
    "mask rcnn",
    "ssd",
    "mobilenet",
    "resnet",
    "vgg",
    "efficientnet",
    "vision transformers",
    "vit",
    "image augmentation",
    "image annotation",
    "pillow",
    "pil",
    "albumentations",
    "detectron2",
    "mediapipe",
    "dlib",
    "open3d",
    "point clouds",
    "3d computer vision",
    "ocr engines",
    "tesseract",
    "easyocr",
    "paddleocr",

    # =========================
    # Natural Language Processing
    # =========================
    "nltk",
    "spacy",
    "gensim",
    "textblob",
    "regex",
    "regular expressions",
    "text preprocessing",
    "stemming",
    "lemmatization",
    "stopword removal",
    "bag of words",
    "tf-idf",
    "tfidf",
    "count vectorizer",
    "word frequency",
    "topic modeling",
    "latent dirichlet allocation",
    "lda",
    "text clustering",
    "language modeling",
    "machine translation",
    "speech recognition",
    "speech to text",
    "text to speech",
    "tts",
    "automatic speech recognition",
    "asr",
    "whisper",
    "voice ai",
    "conversational ai",
    "chatbots",
    "dialogue systems",
    "information retrieval",
    "document classification",
    "document parsing",
    "resume parsing",
    "pdf parsing",
    "text extraction",
    "pdfplumber",
    "pypdf",
    "pypdf2",
    "python-docx",
    "docx",
    "beautifulsoup",
    "beautifulsoup4",
    "scrapy",
    "web scraping",
    "selenium",
    "playwright",

    # =========================
    # Cloud Computing
    # =========================
    "cloud computing",
    "cloud architecture",
    "cloud infrastructure",
    "aws",
    "amazon web services",
    "azure",
    "microsoft azure",
    "gcp",
    "google cloud platform",
    "google cloud",
    "oracle cloud",
    "ibm cloud",
    "alibaba cloud",
    "digitalocean",
    "heroku",
    "vercel",
    "netlify",
    "render",
    "railway",
    "aws ec2",
    "aws s3",
    "aws lambda",
    "aws rds",
    "aws dynamodb",
    "aws elastic beanstalk",
    "aws cloudformation",
    "aws cloudwatch",
    "aws iam",
    "aws vpc",
    "aws sns",
    "aws sqs",
    "aws api gateway",
    "aws ecs",
    "aws eks",
    "aws ecr",
    "aws fargate",
    "aws glue",
    "aws athena",
    "aws redshift",
    "aws sagemaker",
    "azure functions",
    "azure devops",
    "azure storage",
    "azure sql",
    "azure kubernetes service",
    "aks",
    "azure virtual machines",
    "azure active directory",
    "microsoft entra id",
    "google compute engine",
    "google cloud storage",
    "google cloud functions",
    "google kubernetes engine",
    "gke",
    "google bigquery",
    "google cloud run",
    "cloud run",
    "cloud storage",
    "cloud security",
    "cloud migration",
    "cloud deployment",
    "cloud networking",

    # =========================
    # DevOps & Infrastructure
    # =========================
    "devops",
    "devsecops",
    "ci/cd",
    "continuous integration",
    "continuous delivery",
    "continuous deployment",
    "docker",
    "docker compose",
    "docker swarm",
    "kubernetes",
    "k8s",
    "helm",
    "jenkins",
    "github actions",
    "gitlab ci",
    "circleci",
    "travis ci",
    "azure pipelines",
    "terraform",
    "ansible",
    "puppet",
    "chef",
    "vagrant",
    "packer",
    "pulumi",
    "argocd",
    "fluxcd",
    "prometheus",
    "grafana",
    "elk stack",
    "elasticsearch",
    "logstash",
    "kibana",
    "fluentd",
    "fluent bit",
    "datadog",
    "new relic",
    "splunk",
    "nagios",
    "zabbix",
    "opentelemetry",
    "linux",
    "ubuntu",
    "debian",
    "centos",
    "red hat",
    "rhel",
    "unix",
    "windows server",
    "nginx",
    "apache",
    "apache http server",
    "haproxy",
    "traefik",
    "load balancing",
    "reverse proxy",
    "infrastructure as code",
    "iac",
    "configuration management",
    "containerization",
    "container orchestration",
    "virtualization",
    "vmware",
    "virtualbox",
    "hyper-v",
    "server administration",
    "system administration",
    "network administration",

    # =========================
    # Version Control
    # =========================
    "git",
    "github",
    "gitlab",
    "bitbucket",
    "azure repos",
    "svn",
    "subversion",
    "mercurial",
    "git branching",
    "git merge",
    "git rebase",
    "git cherry-pick",
    "git stash",
    "git hooks",
    "pull requests",
    "code review",
    "version control",
    "source control",

    # =========================
    # Cybersecurity
    # =========================
    "cybersecurity",
    "information security",
    "network security",
    "application security",
    "cloud security",
    "ethical hacking",
    "penetration testing",
    "vulnerability assessment",
    "vulnerability scanning",
    "security testing",
    "penetration testing tools",
    "kali linux",
    "metasploit",
    "burp suite",
    "wireshark",
    "nmap",
    "nessus",
    "openvas",
    "sqlmap",
    "hydra",
    "john the ripper",
    "aircrack-ng",
    "owasp",
    "owasp top 10",
    "owasp zap",
    "cryptography",
    "encryption",
    "decryption",
    "symmetric encryption",
    "asymmetric encryption",
    "aes",
    "rsa",
    "sha",
    "hashing",
    "digital signatures",
    "public key infrastructure",
    "pki",
    "ssl",
    "tls",
    "firewalls",
    "vpn",
    "intrusion detection",
    "intrusion prevention",
    "ids",
    "ips",
    "siem",
    "security information and event management",
    "zero trust",
    "identity and access management",
    "iam",
    "access control",
    "authentication",
    "authorization",
    "multi-factor authentication",
    "mfa",
    "security auditing",
    "incident response",
    "digital forensics",
    "malware analysis",
    "threat intelligence",
    "security operations",
    "soc",
    "endpoint security",
    "network monitoring",
    "password security",
    "secure coding",
    "secure software development",
    "penetration testing",
    "burp",

    # =========================
    # Mobile Development
    # =========================
    "android",
    "android studio",
    "android sdk",
    "android development",
    "ios",
    "ios development",
    "swiftui",
    "uikit",
    "react native",
    "flutter",
    "dart",
    "xamarin",
    "maui",
    "ionic",
    "cordova",
    "kotlin multiplatform",
    "mobile application development",
    "mobile ui",
    "mobile testing",
    "firebase cloud messaging",
    "push notifications",
    "mobile apis",
    "mobile app deployment",

    # =========================
    # Testing & Quality Assurance
    # =========================
    "software testing",
    "testing",
    "quality assurance",
    "qa",
    "unit testing",
    "integration testing",
    "system testing",
    "functional testing",
    "regression testing",
    "smoke testing",
    "sanity testing",
    "acceptance testing",
    "user acceptance testing",
    "uat",
    "end to end testing",
    "e2e testing",
    "performance testing",
    "load testing",
    "stress testing",
    "security testing",
    "api testing",
    "automation testing",
    "test automation",
    "selenium",
    "selenium webdriver",
    "pytest",
    "unittest",
    "jest",
    "mocha",
    "chai",
    "junit",
    "testng",
    "cypress",
    "playwright",
    "postman",
    "newman",
    "soapui",
    "rest assured",
    "locust",
    "jmeter",
    "gatling",
    "k6",
    "appium",
    "robot framework",
    "cucumber",
    "behave",
    "test cases",
    "test scripts",
    "test plans",
    "test execution",
    "bug tracking",
    "bug reporting",
    "defect tracking",
    "test management",
    "test-driven development",
    "tdd",
    "behavior-driven development",
    "bdd",
    "mocking",
    "unit test mocking",
    "code coverage",
    "sonarqube",
    "static code analysis",
    "continuous testing",

    # =========================
    # Tools & Platforms
    # =========================
    "jira",
    "confluence",
    "trello",
    "asana",
    "notion",
    "figma",
    "adobe xd",
    "postman",
    "insomnia",
    "swagger",
    "openapi",
    "power bi",
    "tableau",
    "excel",
    "microsoft excel",
    "power query",
    "power pivot",
    "dax",
    "sap",
    "salesforce",
    "servicenow",
    "hubspot",
    "zoho",
    "quickbooks",
    "splunk",
    "datadog",
    "grafana",
    "kibana",
    "jupyter",
    "jupyter notebook",
    "jupyterlab",
    "google colab",
    "kaggle",
    "anaconda",
    "pycharm",
    "visual studio",
    "vs code",
    "visual studio code",
    "intellij idea",
    "eclipse",
    "netbeans",
    "android studio",
    "xcode",
    "rstudio",
    "matlab",
    "docker desktop",
    "virtual studio code",
    "npm",
    "yarn",
    "pnpm",
    "pip",
    "conda",
    "maven",
    "gradle",
    "nuget",
    "composer",
    "cargo",
    "homebrew",
    "make",
    "cmake",

    # =========================
    # Project Management - Technical
    # =========================
    "agile",
    "scrum",
    "kanban",
    "waterfall",
    "software development lifecycle",
    "sdlc",
    "system development lifecycle",
    "requirements engineering",
    "requirements analysis",
    "software architecture",
    "technical documentation",
    "api documentation",
    "software design",
    "system architecture",
    "architecture design",
    "technical specification",
    "functional requirements",
    "non-functional requirements",
    "use case modeling",
    "uml",
    "unified modeling language",
    "version management",
    "release management",
    "deployment management",
    "configuration management",
    "change management",
    "incident management",
    "problem management",
    "service management",
    "itil",
    "risk analysis",
    "risk assessment",
    "capacity planning",
    "performance monitoring",
    "technical project management",

    # =========================
    # Software Concepts
    # =========================
    "oop",
    "object oriented programming",
    "object-oriented programming",
    "data structures",
    "algorithms",
    "data structures and algorithms",
    "dsa",
    "problem solving",
    "debugging",
    "software development",
    "software engineering",
    "computer science",
    "operating systems",
    "computer networks",
    "database management systems",
    "dbms",
    "computer architecture",
    "compiler design",
    "distributed systems",
    "system design",
    "low level design",
    "high level design",
    "lld",
    "hld",
    "design patterns",
    "solid principles",
    "clean code",
    "clean architecture",
    "domain driven design",
    "ddd",
    "test driven development",
    "tdd",
    "behavior driven development",
    "bdd",
    "functional programming",
    "procedural programming",
    "concurrent programming",
    "parallel programming",
    "multithreading",
    "multiprocessing",
    "asynchronous programming",
    "asyncio",
    "concurrency",
    "parallelism",
    "memory management",
    "garbage collection",
    "recursion",
    "dynamic programming",
    "greedy algorithms",
    "backtracking",
    "graph algorithms",
    "tree algorithms",
    "sorting algorithms",
    "searching algorithms",
    "binary search",
    "hashing",
    "hash tables",
    "stacks",
    "queues",
    "linked lists",
    "arrays",
    "strings",
    "trees",
    "graphs",
    "heaps",
    "tries",
    "binary trees",
    "binary search trees",
    "avl trees",
    "red black trees",
    "priority queues",
    "time complexity",
    "space complexity",
    "big o notation",
    "memory optimization",
    "performance optimization",
    "code optimization",
    "refactoring",
    "code quality",
    "software maintenance",
    "legacy code",
    "technical debt",

    # =========================
    # Blockchain & Web3
    # =========================
    "blockchain",
    "web3",
    "ethereum",
    "bitcoin",
    "smart contracts",
    "solidity",
    "hyperledger",
    "hyperledger fabric",
    "web3.js",
    "ethers.js",
    "truffle",
    "hardhat",
    "metamask",
    "decentralized applications",
    "dapps",
    "defi",
    "nft",
    "non-fungible tokens",
    "cryptocurrency",
    "consensus algorithms",
    "proof of work",
    "proof of stake",
    "distributed ledger technology",

    # =========================
    # IoT & Embedded Systems
    # =========================
    "iot",
    "internet of things",
    "embedded systems",
    "embedded c",
    "arduino",
    "raspberry pi",
    "esp32",
    "esp8266",
    "microcontrollers",
    "microprocessors",
    "robotics",
    "sensors",
    "actuators",
    "mqtt",
    "coap",
    "modbus",
    "can bus",
    "embedded linux",
    "real-time systems",
    "rtos",
    "freeRTOS",
    "firmware",
    "hardware programming",
    "circuit design",
    "pcb design",
    "verilog",
    "vhdl",
    "fpga",
    "computer engineering",

    # =========================
    # Big Data
    # =========================
    "big data",
    "hadoop",
    "hdfs",
    "mapreduce",
    "apache spark",
    "spark sql",
    "pyspark",
    "apache hive",
    "apache pig",
    "apache kafka",
    "apache flink",
    "apache storm",
    "apache beam",
    "apache airflow",
    "databricks",
    "delta lake",
    "lakehouse",
    "data warehouse",
    "data lake",
    "data pipeline",
    "stream processing",
    "batch processing",
    "real-time analytics",
    "distributed computing",
    "data ingestion",
    "data orchestration",

    # =========================
    # Miscellaneous Technical
    # =========================
    "ui/ux",
    "user interface",
    "user experience",
    "wireframing",
    "prototyping",
    "design systems",
    "information architecture",
    "responsive web design",
    "accessibility",
    "seo",
    "search engine optimization",
    "technical seo",
    "web performance",
    "web analytics",
    "google analytics",
    "google tag manager",
    "content management systems",
    "cms",
    "wordpress development",
    "e-commerce",
    "ecommerce",
    "shopify",
    "woocommerce",
    "payment gateway integration",
    "stripe",
    "razorpay",
    "paypal",
    "email automation",
    "smtp",
    "twilio",
    "sendgrid",
    "firebase",
    "push notification",
    "cron jobs",
    "task scheduling",
    "background jobs",
    "message queues",
    "rabbitmq",
    "apache activemq",
    "celery",
    "redis queue",
    "rq",
    "caching",
    "cdn",
    "content delivery network",
    "file upload",
    "file processing",
    "pdf generation",
    "pdf extraction",
    "document processing",
    "image processing",
    "audio processing",
    "video processing",
    "ffmpeg",
    "opencv",
    "computer graphics",
    "game development",
    "unity",
    "unreal engine",
    "godot",
    "three.js",
    "webgl",
    "opengl",
    "directx",
    "3d modeling",
    "blender",
    "autocad",
    "mathematica",
    "simulink",
    "latex",
    "markdown",
    "xml",
    "json",
    "yaml",
    "toml",
    "csv",
    "parquet",
    "avro",
    "protobuf",
    "messagepack",

]